"""Add invites table; Update users table

Revision ID: 032f2bef8d8d
Revises: 5c8c426595b0
Create Date: 2025-03-19 20:12:38.425398

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "032f2bef8d8d"
down_revision: Union[str, None] = "579d48dd94ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invites",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), unique=True, nullable=False),
        sa.Column("hash_code", sa.String(), unique=True, nullable=False),
        sa.Column("clicks", sa.Integer(), default=0),
        sa.Column("created_at", sa.DateTime(), default=sa.func.now()),
        sa.Column("is_active", sa.Boolean(), default=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
    )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_invite_name", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invites")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("source_invite_name")

    # ### end Alembic commands ###
