"""user_trial_period_and_referral_model

Revision ID: 0d6e179d7d34
Revises: 5c8c426595b0
Create Date: 2025-03-11 13:54:42.811224

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d6e179d7d34"
down_revision: Union[str, None] = "5c8c426595b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("referred_tg_id", sa.Integer(), nullable=False),
        sa.Column("referrer_tg_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("referred_rewarded_at", sa.DateTime(), nullable=True),
        sa.Column("referrer_rewarded_at", sa.DateTime(), nullable=True),
        sa.Column("bonus_days", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referred_tg_id"],
            ["users.tg_id"],
            name=op.f("fk_referrals_referred_tg_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["referrer_tg_id"],
            ["users.tg_id"],
            name=op.f("fk_referrals_referrer_tg_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referrals")),
        sa.UniqueConstraint("referred_tg_id", name=op.f("uq_referrals_referred_tg_id")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_trial_used", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_trial_used")

    op.drop_table("referrals")
    # ### end Alembic commands ###
