"""delete subscription url for server

Revision ID: 3a79f6c8490e
Revises: dbf2ed0f9dad
Create Date: 2025-02-18 18:19:52.827382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a79f6c8490e"
down_revision: Union[str, None] = "dbf2ed0f9dad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_column("subscription")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subscription",
                sa.VARCHAR(length=255),
                nullable=True,
            )
        )

    op.execute("UPDATE servers SET subscription = '' WHERE subscription IS NULL")

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.alter_column(
            "subscription",
            nullable=False,
        )
    # ### end Alembic commands ###
