"""referrer_rewards

Revision ID: 579d48dd94ef
Revises: 0d6e179d7d34
Create Date: 2025-03-23 00:09:34.785225

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "579d48dd94ef"
down_revision: Union[str, None] = "0d6e179d7d34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("referrals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("referred_bonus_days", sa.Integer(), nullable=True))
        batch_op.drop_column("referrer_rewarded_at")
        batch_op.drop_column("bonus_days")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("referrals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bonus_days", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("referrer_rewarded_at", sa.DATETIME(), nullable=True))
        batch_op.drop_column("referred_bonus_days")

    # ### end Alembic commands ###
