"""fix promocode

Revision ID: 5c8c426595b0
Revises: 3a79f6c8490e
Create Date: 2025-02-21 18:38:53.093866

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c8c426595b0"
down_revision: Union[str, None] = "3a79f6c8490e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("promocodes", schema=None) as batch_op:
        batch_op.alter_column(
            "code",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.String(length=32),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("promocodes", schema=None) as batch_op:
        batch_op.alter_column(
            "code",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
