"""add plan in transaction table

Revision ID: 9728d4a4062e
Revises: ab82cd81e579
Create Date: 2025-01-09 13:34:09.612172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9728d4a4062e'
down_revision: Union[str, None] = 'ab82cd81e579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plan', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'plan')
    # ### end Alembic commands ###
