"""update transaction status enum

Revision ID: 9aa6ddb8e352
Revises: 1f557db4f100
Create Date: 2025-02-05 19:25:06.863986

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aa6ddb8e352"
down_revision: Union[str, None] = "1f557db4f100"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    new_enum = sa.Enum("pending", "completed", "canceled", "refunded", name="transactionstatus")

    op.create_table(
        "transactions_new",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.String(length=64), nullable=False),
        sa.Column("subscription", sa.String(length=255), nullable=False),
        sa.Column("status", new_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["users.tg_id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", name="uq_transactions_payment_id"),
    )

    op.execute(
        "INSERT INTO transactions_new SELECT id, tg_id, payment_id, subscription, "
        "CASE WHEN status = 'failed' THEN 'canceled' ELSE status END, "
        "created_at, updated_at FROM transactions"
    )

    op.drop_table("transactions")
    op.rename_table("transactions_new", "transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    old_enum = sa.Enum("pending", "completed", "failed", "refunded", name="transactionstatus")

    op.create_table(
        "transactions_new",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.String(length=64), nullable=False),
        sa.Column("subscription", sa.String(length=255), nullable=False),
        sa.Column("status", old_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["users.tg_id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", name="uq_transactions_payment_id"),
    )

    op.execute(
        "INSERT INTO transactions_new SELECT id, tg_id, payment_id, subscription, "
        "CASE WHEN status = 'canceled' THEN 'failed' ELSE status END, "
        "created_at, updated_at FROM transactions"
    )

    op.drop_table("transactions")
    op.rename_table("transactions_new", "transactions")
    # ### end Alembic commands ###
