"""add servers table

Revision ID: 9c2a4aefa934
Revises: 64aa21a85c47
Create Date: 2024-12-29 11:17:52.168263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2a4aefa934'
down_revision: Union[str, None] = '64aa21a85c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('subscription', sa.String(length=255), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('current_clients', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    # ### end Alembic commands ###
