"""add online in servers table

Revision ID: ab82cd81e579
Revises: 9c2a4aefa934
Create Date: 2024-12-30 19:41:55.261969

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab82cd81e579"
down_revision: Union[str, None] = "9c2a4aefa934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Need to delete the database!
    op.add_column("servers", sa.Column("online", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("servers", "online")
    # ### end Alembic commands ###
