"""add trial used for user

Revision ID: add_trial_used_for_user
Revises: 5c8c426595b0
Create Date: 2024-03-13 08:14:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_trial_used_for_user"
down_revision: Union[str, None] = "5c8c426595b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("trial_used", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "trial_used")
    # ### end Alembic commands ### 