"""refactor models

Revision ID: d5626cdd1dcd
Revises: 9728d4a4062e
Create Date: 2025-01-16 22:47:08.148811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5626cdd1dcd"
down_revision: Union[str, None] = "9728d4a4062e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("promocodes", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_promocodes_activated_by_users",
            "users",
            ["activated_by"],
            ["id"],
        )
    op.add_column("transactions", sa.Column("subscription", sa.String(length=255), nullable=False))
    op.drop_column("transactions", "amount")
    op.drop_column("transactions", "plan")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("plan", sa.VARCHAR(length=64), nullable=False))
    op.add_column("transactions", sa.Column("amount", sa.FLOAT(), nullable=False))
    op.drop_column("transactions", "subscription")
    with op.batch_alter_table("promocodes", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_promocodes_activated_by_users",
            type_="foreignkey",
        )
    # ### end Alembic commands ###
