"""add language_code for user

Revision ID: dbf2ed0f9dad
Revises: 9aa6ddb8e352
Create Date: 2025-02-15 18:29:10.660892

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbf2ed0f9dad"
down_revision: Union[str, None] = "9aa6ddb8e352"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language_code", sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("language_code")

    # ### end Alembic commands ###
